# Generated by Django 3.2.5 on 2021-07-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('description', models.TextField(max_length=500)),
                ('category', models.IntegerField(choices=[(0, 'sport'), (1, 'hobby'), (2, 'student'), (3, 'none')], default=3)),
                ('priority', models.IntegerField(choices=[(0, 'بی اهمیت'), (1, 'کم اهمیت'), (2, 'توجه'), (3, 'قابل توجه'), (4, 'مهم'), (5, 'ضروری')], default=0)),
                ('expired', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('expired',),
            },
        ),
    ]
