# Generated by Django 3.2.5 on 2021-07-27 17:07

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('expire_task', django.db.models.manager.Manager()),
            ],
        ),
    ]
